name: Node - Setup - Workflow
on: 
  push:
   branches:
      - "*"

jobs:
  node-setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v5

      - name: Setup node js
        uses: actions/setup-node@v5
        with:
         node-version: '18'

      - name: Install dependencies
        run: 
            npm install
            node index.js
    
